---
root: true

plugins:
  - "@typescript-eslint"
  - eslint-comments
  - jest
  - import
  - promise

extends:
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:eslint-comments/recommended
  - plugin:jest/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:promise/recommended
  - prettier # eslint-config-prettier

env:
  es6: true
  node: true
  jest/globals: true

parserOptions:
  project: ./tsconfig.eslint.json

rules:
  no-console: off
  "@typescript-eslint/no-unused-vars": [1, { argsIgnorePattern: "^_" }]
  "@typescript-eslint/no-explicit-any": 0

parser: "@typescript-eslint/parser"

settings:
  import/resolver:
    typescript:
      project: .
