---
root: true

env:
  es6: true
  node: true
  jest/globals: true

parser: "@typescript-eslint/parser"

parserOptions:
  project: ./tsconfig.eslint.json

plugins:
  - "@typescript-eslint"
  - jest
  - import

extends:
  - airbnb-typescript/base
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - prettier # eslint-config-prettier

settings:
  import/resolver:
    typescript:
      project: .

rules:
  no-console: off
  "@typescript-eslint/no-unused-vars": [1, { argsIgnorePattern: "^_" }]
  "@typescript-eslint/no-explicit-any": 0
